# Generated by Django 2.2.2 on 2019-07-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0002_auto_20190701_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('sub', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField()),
            ],
        ),
    ]
