# Generated by Django 2.2.2 on 2019-07-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0003_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='itemjson',
            field=models.CharField(blank=True, max_length=5200),
        ),
    ]
